name: Test Runner
on:
  push:
    branches:
      - main
jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Verification
        shell: powershell
        run: echo "Test de fonctionnement du Runner sur Windows !"

      - name: Tests de commandes système
        shell: powershell
        run: |
          echo "Nom de la machine :"
          hostname
          echo "Utilisateur actuel :"
          whoami
          echo "Version du système :"
          cmd /c ver